### ISSUE TITLE
Have problem 

### ISSUE THREAD

**Issue by nicejava** [git-elliot/Boolean-Calculator#1]
![image](https://user-images.githubusercontent.com/6760497/78117042-5bc2cf00-742f-11ea-9c4e-278427088018.png)

How to solved ?

**Comment by nicejava** [comment]
after use command "gcc bcalc.tab.c -ll -ly"

**Comment by git-elliot** [comment]
As I can see in screenshot, your system is Windows. But this project was created and compiled on linux machine.
